version: "3.8"
services:
    db:
      image: postgres:latest
      environment:
        PGDATA: /var/lib/postgresql/data/some_name/
        POSTGRES_PASSWORD: ipadib339
      volumes:
        - data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
    server:
      container_name: server
      image: node:latest
      command: sh -c "npm install && npm run dev"
      volumes:
        - ./backend:/usr/src/server
      working_dir: /usr/src/server
      ports:
        - "9001:9001"
      depends_on: 
        - db
volumes:
  data: {}
